name: Build and Test .NET Project

on:
  push:
    branches:
      - client
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for pushing to master

      # 3. Restore NuGet packages
      - name: Restore NuGet Packages
        run: dotnet restore generated-client/FactsetEstimatesClient.sln

      # 4. Build the solution in Release mode
      - name: Test Solution
        run: |
          $env:Factset__Username="myuser"
          $env:Factset__Password="mypassword"
          dotnet generated-client/src/FactsetEstimatesClient.Test/FactsetEstimatesClient.Test.csproj

